routes:
  /thong-bao/:
    template: thong-bao
  /lien-he/:
    template: lien-he 

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
