routes:
  /thong-bao/:
    template: thong-bao
  /lien-he/:
    template: lien-he 
  /van-ban/:
    template: van-ban
  /hoat-dong/:
    template: hoat-dong
  /check-uuid/:
    template: check-uuid
collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
